[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings=['@openzeppelin/contracts=lin/openzeppelin-contracts/contracts']

[fuzz]
runs = 600
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[rpc_endpoints]
mainnet="{MAINNET_RPC_URL}"
